In [3]:
import numpy as np

In [4]:
u = np.array([4, ])
u

array([4, 3])

In [5]:
v = np.array([4, 8, 1])
v

array([1, 2])

In [6]:
u + v

array([5, 5])

In [7]:
w = u-v
w

array([3, 1])

In [8]:
# Cuidado: u*v não é produto escalar
p = u*v
p
# É apenas uma multiplicação elemento a elemento

array([4, 6])

**Produto escalar ou produto interno (inner) ou dot product**

In [9]:
# usando a função inner do módulo numpy
np.inner(u,v)

10

In [10]:
# usando a função dot do módulo numpy
np.dot(u,v)

10

In [12]:
# usando o símbolo @ de python

In [ ]:
u@v

10

**Calculando módulo ou norma utilizando a sublib linalg**

In [ ]:
np.linalg.norm(u)

5.0

In [ ]:
# Importando apenas a função norm
from numpy.linalg import norm
norm(u)

5.0

**Ângulo entre vetores**

In [ ]:
print(u)
print(v)

[4 3]
[1 2]


In [ ]:
cosseno =u@v/(norm(u)*norm(v))
cosseno

0.8944271909999159

In [ ]:
ang = np.arccos(0.5)
ang
# a resposta sai em radianos

1.0471975511965979

In [ ]:
np.rad2deg(ang)

60.00000000000001

In [ ]:
np.deg2rad(180)

3.141592653589793

In [ ]:
cosseno =u@v/(norm(u)*norm(v))
cosseno

0.8944271909999159

In [ ]:
ang=np.arccos(cosseno)
ang

0.46364760900080615

In [ ]:
ang = np.rad2deg(ang)
ang

26.565051177077994

**Produto vetorial ou cross product**

In [13]:
a = np.array([4, 2, 3])

In [14]:
b = np.array([3, 1, 1])

In [15]:
c = np.cross(a,b)

In [18]:
norm(c)

NameError: ignored

In [ ]:
np.sqrt(9)

3.0

In [ ]:
9**(1/2)

3.0